name: kubsau_schedule
description: A new Flutter project.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  collection: ^1.17.1
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.0.2
  dio: ^5.3.2
  dio_smart_retry: ^5.0.0
  dynamic_color: ^1.6.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  go_router: ^11.0.0
  hooks_riverpod: ^2.4.0
  intl: ^0.18.1
  package_info_plus: ^4.0.2
  path: ^1.8.3
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.2.1
  yaml: ^3.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

# Task definition for derry
scripts: derry.yaml
